[package]
name = "latex-remixicon"
version = "0.1.0"
edition = "2021"

[dependencies]
convert_case = "0.6.0"
regex = "^1.11.1"
serde = { version = "1.0.215", features = ["derive"] }
serde_json = "1.0.132"

[[bin]]
name = "latex-remixicon"
path = "main.rs"
